openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /academiciens:
    get:
      operationId: academiciens_retrieve
      tags:
      - academiciens
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /motif/:
    get:
      operationId: motif_list
      tags:
      - motif
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Motif'
          description: ''
    post:
      operationId: motif_create
      tags:
      - motif
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Motif'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Motif'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Motif'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Motif'
          description: ''
  /motif/{id}/:
    get:
      operationId: motif_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this motif.
        required: true
      tags:
      - motif
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Motif'
          description: ''
    put:
      operationId: motif_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this motif.
        required: true
      tags:
      - motif
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Motif'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Motif'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Motif'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Motif'
          description: ''
    patch:
      operationId: motif_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this motif.
        required: true
      tags:
      - motif
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedMotif'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedMotif'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedMotif'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Motif'
          description: ''
    delete:
      operationId: motif_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this motif.
        required: true
      tags:
      - motif
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /paiement/:
    get:
      operationId: paiement_list
      tags:
      - paiement
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payement'
          description: ''
    post:
      operationId: paiement_create
      tags:
      - paiement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payement'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Payement'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Payement'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payement'
          description: ''
  /paiement/{id}/:
    get:
      operationId: paiement_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this payement.
        required: true
      tags:
      - paiement
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payement'
          description: ''
    put:
      operationId: paiement_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this payement.
        required: true
      tags:
      - paiement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payement'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Payement'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Payement'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payement'
          description: ''
    patch:
      operationId: paiement_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this payement.
        required: true
      tags:
      - paiement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPayement'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPayement'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPayement'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payement'
          description: ''
    delete:
      operationId: paiement_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this payement.
        required: true
      tags:
      - paiement
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Motif:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        libelle:
          type: string
          maxLength: 200
      required:
      - id
      - libelle
    PatchedMotif:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        libelle:
          type: string
          maxLength: 200
    PatchedPayement:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        id_academicien:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        id_motif:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        date:
          type: string
          format: date
        heure:
          type: string
          format: time
        montant:
          type: string
          format: decimal
          pattern: ^\d{0,6}(?:\.\d{0,2})?$
    Payement:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        id_academicien:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        id_motif:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        date:
          type: string
          format: date
        heure:
          type: string
          format: time
        montant:
          type: string
          format: decimal
          pattern: ^\d{0,6}(?:\.\d{0,2})?$
      required:
      - date
      - heure
      - id
      - id_academicien
      - id_motif
      - montant
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
